WIP: Sampler overhaul
noegroup/bgflow pull request #23
Opened 2021-09-30 08:31 UTC by Olllom

Draft for a new iterative sampler API  + data samplers and metropolized replay buffer.

2021-10-04 19:32 UTC, Olllom reviewed
A few explanations. Everything else should hopefully be clear from the docstrings.

2021-10-04 19:32 UTC, Olllom commented on bgflow/bg.py
the only change in this file is that the distinctions between tensors and tuples-of-tensors are now handled by the new `pack_tensor_in_tuple` function.

2021-10-04 19:32 UTC, Olllom commented on .github/workflows/CI.yml
>        - name: Install dependencies
Here, I am just introducing NetCDF4 as a dependency for the pip-tests. This is an optional dependency to support writing to a kind of trajectory file.

2021-10-04 19:32 UTC, Olllom commented on bgflow/distribution/sampling/base.py
>  class Sampler(torch.nn.Module):
This now has a `return_hook` to do something with the samples (e.g. reshaping or selecting elements) before they are returned.

2021-10-04 19:32 UTC, Olllom commented on bgflow/nn/flow/sequential.py
> +        dlogp = 0.0
This removes the assumption that we only have one event shape.

2021-10-04 19:32 UTC, Olllom commented on bgflow/distribution/sampling/mcmc.py
> +"""Markov-Chain Monte Carlo iterative sampling.
This file now implements the more general Monte Carlo sampling stuff.
I am also leaving the old implementation in for backwards-compatibility. But I want to take it out as soon as we have a working TSF notebook.

2021-10-07 08:08 UTC, Olllom commented on bgflow/distribution/sampling/iterative.py
> +class SamplerState(dict):
Implement as Dataclass?

2022-01-18 15:32 UTC, jonkhler requested changes

2022-02-15 23:03 UTC, merged